## Question 1
Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original 3x3 Array:")
print(array)

# Step 2: Interchange rows and columns (transpose the matrix)
transposed_array = array.T
print("\nTransposed 3x3 Array:")
print(transposed_array)


Original 3x3 Array:
[[28 94 46]
 [45 16 47]
 [51 26 95]]

Transposed 3x3 Array:
[[28 45 51]
 [94 16 26]
 [46 47 95]]


## Question 2
Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


In [2]:
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)  # Array with elements from 1 to 10
print("1D Array with 10 Elements:")
print(array_1d)

# Step 2: Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Step 3: Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(array_5x2)


1D Array with 10 Elements:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped into 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped into 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


## Question 3
Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [3]:
import numpy as np

# Step 1: Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Step 2: Add a border of zeros, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(array_6x6)


Original 4x4 Array:
[[0.34004835 0.04326545 0.69211847 0.94464491]
 [0.07624145 0.0584011  0.21501156 0.56442088]
 [0.70199158 0.66331791 0.05573926 0.43856183]
 [0.70362775 0.21991265 0.04333542 0.99877628]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.34004835 0.04326545 0.69211847 0.94464491 0.        ]
 [0.         0.07624145 0.0584011  0.21501156 0.56442088 0.        ]
 [0.         0.70199158 0.66331791 0.05573926 0.43856183 0.        ]
 [0.         0.70362775 0.21991265 0.04333542 0.99877628 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


## Question 4
Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array of Integers from 10 to 60 with Step 5:")
print(array)


Array of Integers from 10 to 60 with Step 5:
[10 15 20 25 30 35 40 45 50 55 60]


## Question 5
Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


In [5]:
import numpy as np

# Step 1: Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])
print("Original Array of Strings:")
print(string_array)

# Step 2: Apply uppercase transformation
uppercase_array = np.char.upper(string_array)
print("\nUppercase Transformation:")
print(uppercase_array)

# Step 3: Apply lowercase transformation
lowercase_array = np.char.lower(string_array)
print("\nLowercase Transformation:")
print(lowercase_array)

# Step 4: Apply title case transformation
titlecase_array = np.char.title(string_array)
print("\nTitle Case Transformation:")
print(titlecase_array)


Original Array of Strings:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']


## Question 6
Generate a NumPy array of words. Insert a space between each character of every word in the array.


In [6]:
import numpy as np

# Step 1: Generate a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])
print("Original Array of Words:")
print(words_array)

# Step 2: Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)
print("\nArray with Spaces Between Each Character:")
print(spaced_words_array)


Original Array of Words:
['python' 'numpy' 'pandas']

Array with Spaces Between Each Character:
['p y t h o n' 'n u m p y' 'p a n d a s']


## Question 7
Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


In [7]:
import numpy as np

# Step 1: Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[6, 5, 4], [3, 2, 1]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Step 2: Perform element-wise addition
addition_result = np.add(array1, array2)
print("\nElement-wise Addition:")
print(addition_result)

# Step 3: Perform element-wise subtraction
subtraction_result = np.subtract(array1, array2)
print("\nElement-wise Subtraction:")
print(subtraction_result)

# Step 4: Perform element-wise multiplication
multiplication_result = np.multiply(array1, array2)
print("\nElement-wise Multiplication:")
print(multiplication_result)

# Step 5: Perform element-wise division
division_result = np.divide(array1, array2)
print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[6 5 4]
 [3 2 1]]

Element-wise Addition:
[[7 7 7]
 [7 7 7]]

Element-wise Subtraction:
[[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication:
[[ 6 10 12]
 [12 10  6]]

Element-wise Division:
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


## Question 8
Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [8]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements of the Identity Matrix:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements of the Identity Matrix:
[1. 1. 1. 1. 1.]


## Question 9
Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


In [9]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)
print("Random Array of 100 Integers:")
print(random_array)

# Step 2: Define a function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

# Step 3: Find and display all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Array of 100 Integers:
[793 461 212 105 808 234  40 797  22 115 338 966 164 711  78 737 741 921
  65 538 818 883 643 962 267 741 897 187 412 224 615 543 782 691 154 866
 968 532 644  59  63 746 532 206 203 884 936 339 178  99 328 989  68 738
 881 733 469 551 779 834 812 761 143 175 454 174 294 211 771 396  39 891
 202 210 686  29  43 737 914 711 965 903 617 981 315 374 462 108 749 504
 352 566 118 271 768 321 117 379 122 264]

Prime Numbers in the Array:
[461, 797, 883, 643, 691, 59, 881, 733, 761, 211, 29, 43, 617, 271, 379]


## Question 10
Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.


In [12]:
import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(20, 35, size=30)  # Temperatures between 20 and 35 degrees Celsius
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Step 2: Reshape the array into 5 weeks (rows) with 6 days (columns)
weekly_temperatures = daily_temperatures.reshape(5, 6)
print("\nWeekly Temperatures (5 weeks x 6 days):")
print(weekly_temperatures)

# Step 3: Calculate and display the weekly averages
weekly_averages = weekly_temperatures.mean(axis=1)
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[34.37101716 34.01200445 28.06498401 20.00737245 23.40160043 29.07394327
 32.0477876  23.29064304 34.71807204 21.45204964 32.06075921 21.26121902
 24.30416951 32.68031817 21.99228658 34.35131119 20.93648727 29.50147245
 31.34046163 20.8274495  30.46689267 32.50684962 29.8979223  21.50652953
 22.06896596 20.65520409 28.21713936 27.35449039 30.4861439  29.58409996]

Weekly Temperatures (5 weeks x 6 days):
[[34.37101716 34.01200445 28.06498401 20.00737245 23.40160043 29.07394327]
 [32.0477876  23.29064304 34.71807204 21.45204964 32.06075921 21.26121902]
 [24.30416951 32.68031817 21.99228658 34.35131119 20.93648727 29.50147245]
 [31.34046163 20.8274495  30.46689267 32.50684962 29.8979223  21.50652953]
 [22.06896596 20.65520409 28.21713936 27.35449039 30.4861439  29.58409996]]

Weekly Averages:
[28.15515363 27.47175509 27.29434086 27.75768421 26.39434061]
